name: Update dataset
on:
    workflow_dispatch:
    schedule:
    - cron: "0 6 * * 3"
jobs:
    download_journals:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
              with:
                  node-version: 18.16.20
            - uses: pnpm/action-setup@v2
              with:
                  version: 8
            - run: pnpm install
            - run: npm run download
            - run: npm run parse
            - run: npm run explore
            - run: |
                  git config user.name github-actions
                  git config user.email github-actions@github.com
                  git add .
                  git commit -m "ci: update dataset" || echo "Nothing to push"
                  git push
